spring.profiles.active=local

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=2

spring.main.banner-mode=off
logging.level.root=WARN

server.port=1111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}

FRONTEND_URL=${FRONTEND_URL}

RESEND_API_KEY=${RESEND_API_KEY}