
spring.profiles.active=local
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.main.banner-mode=off
logging.level.root=WARN
server.port=1111
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}