spring.application.name=SignalForge

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=5

spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.signalforge=INFO
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.tool.schema=INFO

server.port=${PORT:1111}

# JPA — Flyway manages schema, Hibernate only validates
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET}

FRONTEND_URL=${FRONTEND_URL:http://localhost:1111}

BREVO_API_KEY=${BREVO_API_KEY}

SENDER_EMAIL=${SENDER_EMAIL:signalforge@gmail.com}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}

COOKIE_SECURE=${COOKIE_SECURE:false}
